### ISSUE TITLE
Create a sentence

### ISSUE THREAD

**Issue by hectoritr** [OTTAA-Project/ottaa_project_flutter#1]
**Is your feature request related to a problem? Please describe.**
- [x] YES
- [x] NO
If YES  please write a clear and concise description of what the problem is. 

**Describe the solution you'd like**
The user should be able to choose one or more pictograms (Big images on the center), when the user chooses one it should go to the top placeholder and stay there, the app should load the related pictograms and display them on the main screen.

**Action Plan**
Add an Action Plan with Checkboxes on key things you have to achieve to complete this task.
- [x] Load Initial Pictograms
- [x] Place the selected pictogram on the Sentence Creator
- [x] Load Related Pictograms
