### ISSUE TITLE
Settings Screen

### ISSUE THREAD

**Issue by hectoritr** [OTTAA-Project/ottaa_project_flutter#10]
**Is your feature request related to a problem? Please describe.**
- NO
If YES  please write a clear and concise description of what the problem is. 

**Describe the solution you'd like**
Implement a Settings screen (See attached) leaving visible only the Settings that are already implemented. 
-Voice & Subtitles
-Language

**Action Plan**
Add an Action Plan with Checkboxes on key things you have to achieve to complete this task.
- [x] Implement Settings Screen
![Screenshot_1625775069](https://user-images.githubusercontent.com/12820318/124984780-043ae800-e010-11eb-8043-5e0d8c4bf772.png)

- [x] Implement Languages, should load all the available voices in the system.  DO NOT implement OTTAA Labs option
![Screenshot_1625775256](https://user-images.githubusercontent.com/12820318/124984792-09983280-e010-11eb-9243-ddc9c1d0f250.png)

- [x] Implement Voice & Subtitles
![Screenshot_1625775261](https://user-images.githubusercontent.com/12820318/124984806-0ef57d00-e010-11eb-92d9-7b703d12bced.png)

**Comment by mal2tin** [comment]
The flutter_tts plugin for web doesn't implement the method 'getVoices'.

**Comment by hectoritr** [comment]
> The flutter_tts plugin for web doesn't implement the method 'getVoices'.

Ok, so you can change only language?
