### ISSUE TITLE
Firebase Analytics 

### ISSUE THREAD

**Issue by hectoritr** [OTTAA-Project/ottaa_project_flutter#12]
**Screenshot of the feature to be developed.**
 
No need

**Describe the solution you'd like**
We need to track the user's interactions with the app, where the users are coming from, etc. 

We need to implement Firebase Analytics to the Firebase project, using the same terminology as the OTTAA Project to be able to aggregate the data, and track accordingly. 

As per Project Readme https://github.com/OTTAA-Project/OTTAAProject#readme

@asimjawad will do one implementation and then @gonojuarez will complete the rest. 

**Action Plan**
Add an Action Plan with Checkboxes on key things you have to achieve to complete this task.

- [ ] Source (Android, Web, iOS)
- [ ] Accesibility
- [x] Talk
- [x] Touch
- [ ] screen_view (Might come with the API)
- [ ] session_start (Might come with the API)

**Comment by hectoritr** [comment]
@asimjawad remember to use Gonzalo for this issue, create one as a template and he will handle the rest!
