### ISSUE TITLE
Pictogram Groups

### ISSUE THREAD

**Issue by hectoritr** [OTTAA-Project/ottaa_project_flutter#13]
**Is your feature request related to a problem? Please describe.**
- [ ] NO
If YES  please write a clear and concise description of what the problem is. 

**Describe the solution you'd like**
We need to have a Galery to navigate through Groups of Pictograms, each Group has an Image, a Text, a row of Tags. 
Each Group contains multiple Pictograms.
The Groups order must be editable.
You can create a Group 
You can search for a specific Pictogram in the Activity Groups. 
Groups can be arranged on a tiles format or one-by-one navigation. 

**Additional context**

**Action Plan**
Add an Action Plan with Checkboxes on key things you have to achieve to complete this task.
- [x] Design Group Screen
- [x] Design Group element
- [x] Implement Pictogram Gallery
- [ ] Sort group Feature
- [x] Search Feature
- [x] One-by-one navigation
