### ISSUE TITLE
[Feat]: Customize Boards Screen

### ISSUE THREAD

**Issue by hectoritr** [OTTAA-Project/ottaa_project_flutter#138]
### Contact Details

-

### What is this about?

As a speech therapist I want to choose what boards the user will have available.  
So that it is easier for them to find what they need, and also for me to plan ahead my therapy sessions. 

You can find the design [here](https://www.figma.com/file/Ro9LZOPdpFcFxCEQbHplmu/Redesign-Ottaa-Project?node-id=1342%3A3239&t=4etDx4gt48cYcflx-0)

**Action Plan**

- [x] customizeBoardScreen UI
- [x] customizeBoardHelpScreen Toast
- [x] populate Board Widget 
- [x] enable/disable Board feature. 

**customizeBoardScreen UI**
This screen is a Listview of all the boards present in the standard dataset. The user can swipe up and down to scroll through all the available boards. 

**customizeBoardHelpScreen Toast**
Display this toast/snackbar if the user presses the help button. 

**populate Board Widget**
Load data from the database with Board Name, Image. The data schema is defined in #77 

**enable/disable Board feature.** 
The user needs to be able to toggle the switch in the Board widget to add/remove this board from the prediction pool

### Where do you want to see this implemented?

Chrome (WebApp), Android, iOS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hectoritr** [comment]
@asimjawad is this fixed? What's in #160 is not ready.

**Comment by asimjawad** [comment]
@emirchus  fix the theme related issue, I am fixing the pinto_widget issue
\

**Comment by hectoritr** [comment]
@asimjawad What's missing to finish this?

**Comment by hectoritr** [comment]
Few things to fix @asimjawad 

- [ ] The user has to be able to modify the pictograms and boards from userMainScreen from button (Tableros/Pictogramas)
- [ ] When linking a user, is not showing the Boards or Pictograms for that specific user.

**Comment by asimjawad** [comment]
on it

**Comment by hectoritr** [comment]
[Error loading Boards.webm](https://user-images.githubusercontent.com/12820318/218482343-2816550e-dea1-4c6d-aee4-79b35bb23d6e.webm)

@asimjawad check this error. Tested on 3 different devices and account. 

Several times I've found this error

**Comment by hectoritr** [comment]
> I've found overflow errors and logic errors.
> 
> * [x]  Database structure is not correct (ask JuanMa about it)
> * [x]  It is storing shortcuts and Pictos in the Caregiver account not in the user account
> * [x]  It is not storing Boards anywhere
> * [ ]  UI errors (and Test them before pushing)
> 
> ![Image](https://user-images.githubusercontent.com/12820318/211315146-55e8a81f-538f-446a-bd4f-a8b7c5fc5faa.jpeg)
> 
> ![Image](https://user-images.githubusercontent.com/12820318/211315186-c6c04068-9498-4604-b7ce-226dee8b16eb.jpeg)
> 
> ![Image](https://user-images.githubusercontent.com/12820318/211315219-ea8a0055-8dea-4509-8127-ab622ebca85f.jpeg)

@asimjawad This is still happening, please open a hotfix branch out of dev and fix it.
