### ISSUE TITLE
[Feat]: Customize Shortcut Screen

### ISSUE THREAD

**Issue by hectoritr** [OTTAA-Project/ottaa_project_flutter#139]
### Contact Details

hcosta@ottaaproject.com

### What is this about?

As a speech therapist, I want to choose what shortcuts the user will have on Main Screen So that he/she has available the right features that suit their needs. 

Design [here](https://www.figma.com/file/Ro9LZOPdpFcFxCEQbHplmu/Redesign-Ottaa-Project?node-id=1342%3A3612&t=4etDx4gt48cYcflx-0)

**Action Plan**

- [x] customizeShortcutScreen 
- [x] add Shortcut selection to data scheme
- [x] show help toast/snackbar

**customizeShortcutScreen**
This screen is a Gridview of all the shortcuts available for the user. By pressing once is selected, pressing again will deselect the shortcut. 

**add Shortcut selection to data scheme**
@lopezjuanma96 will add this to the data schema. 
When the user press "Continue" button, the selection needs to be saved for use in the user's device. 

**show help toast/snackbar**
Display this toast/snackbar if the user presses the help button.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by emirchus** [comment]
@asimjawad did this issue in #150
