### ISSUE TITLE
[Feat]: profileMainScreen with User Menu

### ISSUE THREAD

**Issue by hectoritr** [OTTAA-Project/ottaa_project_flutter#157]
### Contact Details

-

### What is this about?

As a caregiver, I want to be able to customize and access all user-related information.  
So that I can plan ahead my sessions, change things and write reports. 

THe design can be found [here](https://www.figma.com/file/Ro9LZOPdpFcFxCEQbHplmu/Redesign-Ottaa-Project?node-id=1342%3A3397&t=u6IuWEeiN0el7drQ-0)

**Action Plan**

- [ ] Load a Linked Account snippet information (Avatar/Image, Name, Last connection)
- [ ] Add Dropdown Menu (Tableros/Pictogramas, Estadisticas, Configuracion, Perfil, Ayuda)
- [ ] "Use OTTAA as" button. 

**Load a Linked Account snippet information**
We need to load a list of all users linked to the caregiver account, the list contains User Snippets with user-related data. 

**Add Dropdown Menu**
If you click the "See profile" text, or click the Snippet the dropdown menu should appear showing all available options for this user such as "Tableros/Pictogramas" Boards&Pictograms, "Estadisticas" Stats, Configuracion "Settings", Perfil "Profile", Ayuda "Help")

**Use OTTAA as button**
If the caregiver press this button, it will go to Main screen as if it was the selected user. 

### Where do you want to see this implemented?

Chrome (WebApp), Android, iOS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by asimjawad** [comment]
go it
