### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by hectoritr** [OTTAA-Project/ottaa_project_flutter#16]
**Is your feature request related to a problem? Please describe.**
- [ ] YES
- [ ] NO
If YES  please write a clear and concise description of what the problem is. 

**Describe the solution you'd like**
Have the app in multiple languages. The app should use the System Language as the default language and then if the user wants to change it should do it from the App Settings

**Additional context**

**Action Plan**
Add an Action Plan with Checkboxes on key things you have to achieve to complete this task.
- [ ] Create a dropdown in Setting to choose the language
- [ ] Load the desired language
- [ ] The app UI, Pictograms, Groups should be in the desired language. 

XML Strings in here
[Strings.zip](https://github.com/OTTAA-Project/ottaa_project_flutter/files/7563333/Strings.zip)

**Comment by hectoritr** [comment]
Catch the case for specific languages, like 
Español Argentina, Español Colombia, etc. 

To prefer Accent and voice for that specific language.
