### ISSUE TITLE
Aesthetic Improvements

### ISSUE THREAD

**Issue by hectoritr** [OTTAA-Project/ottaa_project_flutter#17]
**Is your feature request related to a problem? Please describe.**
- [ ] YES
- [ ] NO
If YES  please write a clear and concise description of what the problem is. 

**Describe the solution you'd like**

**Additional context**

**Action Plan**
Add an Action Plan with Checkboxes on key things you have to achieve to complete this task.
- [ ] Task A
- [ ] Task B

**Comment by hectoritr** [comment]
Here is the documentation file for the Aesthetics changes needed

https://docs.google.com/document/d/19leNb5DQ2RaC1I7yG-gU707wWlB4wcDLex65-WhFXws/edit?hl=es#

Please add comments as needed.

**Comment by asimjawad** [comment]
need the photos for the user selection.

**Comment by hectoritr** [comment]
Hi Asim, you have been shared a Drive folder with the designs and the assets. Please let me know if you need further clarification on this!

**Comment by hectoritr** [comment]
Comments for review. 

Still showing texts in English when my browser is in Spanish.

Login Screen 1: OK

Login Screen 2: 

- [ ] More separation between the Big Title and the little text.
- [ ] All highlights are Blue, should be Orange (Name EditText)
- [ ] MALE and FEMALE should not be Caps Locks
- [ ] Date picker still blue.

Login Screen 3:

- [ ] Big title should be bigger, same size as previous screen
- [ ] More separation between Big Title and little text.
- [ ] After the short tutorial should go back to the same screen, to do another tutorial or to press "Next" and choose the Avatar.

Login Screen 4:

- [ ] All Big Title should be at the same high on the screen and have the same font size
- [ ] Remove Tutorial Slides when pressing Next, should go to Main Screen

Main Screen:

- [ ] Make the placeholder for Pictos, the same size when there is a picto in them. 
- [ ] With long text on the Pictos the color frames are misaligned. 

Grupos:

- [ ] Make background color same as Main Screen
- [ ] Make the width of the orange control bar same as Main Screen.

**Comment by asimjawad** [comment]
- [ Language for web version]  still looking for a native method which can work on both web and app.

**Comment by asimjawad** [comment]
Added a fix for the web version for language.

**Comment by hectoritr** [comment]
Central Button. 

- [ ] Need to implement a central button, with a similar look of the one in the Android App, button should have a  bottom margin, and should go over the Orange bar by 5%.

<img width="680" alt="Captura de Pantalla 2021-12-09 a la(s) 11 30 53" src="https://user-images.githubusercontent.com/12820318/145416716-cd902279-b1f7-45d2-add1-bc6a1312bc5d.png">

In main screen, this button should make the app Speak.
- [ ] Make the app speak

In Groups, this button should enter the selected category when in Single view mode

- [ ] Enter to the category in Single View mode.

**Comment by hectoritr** [comment]
Remaining things
- [ ] Fix Pictogram Gallery, with same sizes 
as Group Gallery. 

- [ ] Fix the aspect ratio on Pictogram Gallery
- [ ] Fix the aspect ratio on Search Screen

- [ ] Add dark background to Search feature,

**Comment by hectoritr** [comment]
> @hectoritr can you add the pictures as a reference to these issues. That will be better for me.

Done! Let's try that the aspect ratio of the images inside the pictograms are all the same and similar to the one on main screen.

**Comment by asimjawad** [comment]
@hectoritr how many Pictos per grid on search tab?

**Comment by asimjawad** [comment]
this closes issue #13

**Comment by hectoritr** [comment]
@asimjawad Please review the Search feature on Groups, it show them on English, should be same as the app language

**Comment by asimjawad** [comment]
Will look into it @hectoritr
