### ISSUE TITLE
Speak!

### ISSUE THREAD

**Issue by hectoritr** [OTTAA-Project/ottaa_project_flutter#2]
**Is your feature request related to a problem? Please describe.**
- [ ] YES
- [x] NO
If YES  please write a clear and concise description of what the problem is. 

**Describe the solution you'd like**
The user must be able to make the app “speak” by pressing the round button in the center bottom or in the top placeholder.
The app should say out loud the created sentence using the text from each selected pictogram and concatenate them.  

**Action Plan**
Add an Action Plan with Checkboxes on key things you have to achieve to complete this task.
- [x] Initialize TTS Engine
- [x] Make the app Speak
- [x] Change language ES/EN
