### ISSUE TITLE
Edit Picto 

### ISSUE THREAD

**Issue by asimjawad** [OTTAA-Project/ottaa_project_flutter#20]
**Screenshot of the feature to be developed.**
 
![Screenshot_1641925689](https://user-images.githubusercontent.com/12820318/149000863-3fdfb6be-c64f-44e2-b59f-bd0927633f36.png)

![Screenshot_1641925706](https://user-images.githubusercontent.com/12820318/149000878-440a4a38-1f6a-4c74-9633-0434e9ebe592.png)

**Describe the solution you'd like**
Any Pictogram or Group should be fully customizable, the Image, Text, Frame and TAGs should be able to be changed. 
To edit a pictogram the user should make a Long Press on the desired Picto or Group and the Menu should appear, the Menu options are Edit or Delete the current pictogram. This long press can be done on Main Screen or in the Gallery.

**Additional context**
Add any other context.

**Action Plan**
Add an Action Plan with Checkboxes on key things you have to achieve to complete this task.
- [x] Design screen UI
- [x] Show Menu when Long Press
- [x] Design Text Tab
- [x] Design Frame Tab
- [ ] Design TAG Tab
- [x] Dialog to choose image source 
- [x] Handle permissions
- [x] Load image from Camera
- [x] Load Image from Gallery
- [x] Load Image from ARASAAC

**Comment by hectoritr** [comment]
NOTE: If for web the camera is hard to implement or not available in different browsers, we can slip it just for WEB

**Comment by hectoritr** [comment]
Find attached the assets requested. 
![pictogramas](https://user-images.githubusercontent.com/12820318/150993900-7107c146-97cc-4887-bf97-af79c0ecac8c.png)

![fotografiar (1)](https://user-images.githubusercontent.com/12820318/150993909-c79836e1-d2e2-461f-bea9-162ead0d9cb1.png)

![álbum fotográfico](https://user-images.githubusercontent.com/12820318/150993923-340c86e8-c4f4-47e9-b54b-bb50974afb99.png)

**Comment by asimjawad** [comment]
thanks @hectoritr

**Comment by hectoritr** [comment]
Re-opening with minor details. 

- [ ] Remove the cloud action button from the top bar, as it is not needed.
- [ ] Remove the + button, as it has no functionality, I'm adding the functionality in a new issue
- [ ] Give a bigger margin to the "Choose Source dialog"
- [ ] Add a dialog that TAGs will come in the next Release
- [ ] Load from Camera is not working, try to loads from Gallery on Mac (Gray image shows in the pictogram) See attached image
- [ ] ARASAAC is not working. See attached pictogram

<img width="1440" alt="Captura de Pantalla 2022-02-16 a la(s) 14 44 10" src="https://user-images.githubusercontent.com/12820318/154324738-c576c26b-488b-4fcc-bbec-09be2fb45c5b.png">

<img width="1440" alt="Captura de Pantalla 2022-02-16 a la(s) 14 44 16" src="https://user-images.githubusercontent.com/12820318/154324758-b0e5bce5-19c4-4346-9865-007ac5d92c2e.png">

**Comment by asimjawad** [comment]
@hectoritr let me try to get my hands on an iPhone to sort this out. It is not possible without having an iPhone.

**Comment by asimjawad** [comment]
@hectoritr let's discuss this in today meetings
