### ISSUE TITLE
Games

### ISSUE THREAD

**Issue by hectoritr** [OTTAA-Project/ottaa_project_flutter#26]
**Is your feature request related to a problem? Please describe.**
- [ ] YES
- [ ] NO
If YES  please write a clear and concise description of what the problem is. 

**Describe the solution you'd like**

**Additional context**

**Action Plan**
Add an Action Plan with Checkboxes on key things you have to achieve to complete this task.
- [ ] Task A
- [ ] Task B

**Comment by asimjawad** [comment]
@gonojuarez  the algorithm and the descriptive working of the games.

**Comment by gonojuarez** [comment]
If the user chooses the correct answer the system increments the correct score, else the system increments the wrong score.

To change the game level, the system reviews the total value which is the result of the plus between correct and wrong answers and makes a verification if the result is divisible by a max number of streaks and returns 0, if that's true the system changes the game level.

The Score( Puntaje) class is really important because this class manage the game scoring to show the level accord the user score.

The Clock (Reloj) class is really important because measures the game time of use

The game (Juego) class is the object that contains different attributes such as Score, Game Level, Emoji by score and Clock.

**Comment by asimjawad** [comment]
@gonojuarez send me the icons used in the menus and the image used on first page

**Comment by hectoritr** [comment]
After testing some issues come up, they need to be fixed before merging. 

What's the Picto

- [ ] Game chooser screen needs to translate
- [ ] Change the String "What's the picto?" for the translation in Spanish "¿Cual es el Picto ?

Match Picto

- [ ] Pictogram aspect ratio is wrong, should be similar to Main Screen or Whats the picto game
- [ ] When chosen correctly, that Picto should align, now they are a bit overlapped, which might be confusing for some people
- [ ] When the user chooses One Picto and then chooses a wrong one, it should "reset" (Needs to touch one to choose and then another to assess if it is right or wrong). Because now the behavior is weird. 


https://user-images.githubusercontent.com/12820318/176493788-d1fb2b47-d822-44bc-82d1-2dc0f21e97a4.mp4



Memory game 

- [ ] Pictogram aspect ratio is wrong, should be similar to Main Screen or Whats the picto game
- [ ] When you choose the second Picto, should stay shown for some time to give time to understand that's the wrong one.
- [ ] When the user chooses correctly all pictos, the Correct Sound should play and the picto should remain shown for some second so the user can understand that a new game started, if not give the feeling that something wrong happened


https://user-images.githubusercontent.com/12820318/176493487-5d821b8a-67c7-4192-b8b4-aeca96f03381.mp4

**Comment by hectoritr** [comment]
@asimjawad There are several bugs on this feature. 

First, still not working on Mac, still throwing the "LateInitializationError: Field 'language' has not been initialized."

On Lenovo, Windows, Chrome 
What's the picto is not showing properly on Lenovo. 

![WhatsApp Image 2022-08-15 at 6 10 08 PM](https://user-images.githubusercontent.com/12820318/184719168-e98fbf71-ac7e-44c7-bf2d-50c2dbd0cb5d.jpeg)


Match Picto
Has a weird behavior, please review the Android version to see how it should work. 
If you touch the text first does not work. 
If you just randomly click a wrong combination of pictos, a random Match is done and shouldn't

Memory game
You can play only once, then the next screen of picto is already solved. (All shown)

**Comment by hectoritr** [comment]
Closed because we are re doing the games.
