### ISSUE TITLE
Report

### ISSUE THREAD

**Issue by hectoritr** [OTTAA-Project/ottaa_project_flutter#27]
**Is your feature request related to a problem? Please describe.**
- [ ] YES
- [ ] NO
If YES  please write a clear and concise description of what the problem is. 

**Describe the solution you'd like**

**Additional context**

**Action Plan**
Add an Action Plan with Checkboxes on key things you have to achieve to complete this task.
- [ ] Task A
- [ ] Task B

**Comment by asimjawad** [comment]
I am facing some difficulties in finding a graph which can shows a smooth line for the flutter, other than that the UI is done
how many most used groups do we need? 
@hectoritr

**Comment by asimjawad** [comment]
@hectoritr  and also send me that little icon on the right side of the most used phrases

**Comment by hectoritr** [comment]
Formula to calculate the score
`// score = last7DaysUsage * a + sentences7days * b + averagePictoFrase * c + usedGroups * d
// maxScore = 7 * a + 700 * b + 5 * c + 44 * d = 10000
//1000 equal one level.`

last7DaysUsage = number of days the user used the app in the last 7 days.
sentences7days = sentences created in the last 7 days.
averagePictoFrase = average pictograms per sentence.
usedGroups = number of different used groups. 

After you gather all these variables
`int a = 500, b = 3, c = 500, d = 44, level = 0, last7DaysUsage = 0, usedGroups = 0;
 double score = 0;
 score = last7DaysUsage * a + frases7days * b + averagePictoFrase * c + usedGroups * d;
 return (int) (score / 1000);`

**Comment by hectoritr** [comment]
> I am facing some difficulties in finding a graph which can shows a smooth line for the flutter, other than that the UI is done how many most used groups do we need? @hectoritr

Let's try with 4, if we can fit them there.

**Comment by asimjawad** [comment]
I will change the UI in the meanwhile to fit 4 of these @hectoritr

**Comment by hectoritr** [comment]
> @hectoritr and also send me that little icon on the right side of the most used phrases

Here you have https://raw.githubusercontent.com/OTTAA-Project/OTTAAProject/master/app/src/main/res/drawable-xhdpi/logo_ottaa_dev.webp

**Comment by hectoritr** [comment]
I've tested the new report and looks great! Few things to solve and it would be good to go. 

- [ ] Not loading any data, check use data.
- [ ] No way of going back to main screen, if you press back on Chrome it closes the whole app.
- [ ] "OTTAA Rencor", should be "OTTAA Score"
- [ ] "FRASES MAS USADAS" is all Caps Lock, Should be Frases Mas Usadas, an font its a big bigger. 
- [ ] Check WTF is 1.5 Sep :) lol On graph. *See image 2

<img width="1440" alt="Screen Shot 2022-09-22 at 22 56 49" src="https://user-images.githubusercontent.com/12820318/191879600-62b6733b-15ce-49a2-93a6-6edceecc99ad.png">

<img width="759" alt="Screen Shot 2022-09-22 at 23 03 31" src="https://user-images.githubusercontent.com/12820318/191879973-cbfc1fe0-6664-45f6-8ef9-86a93823ce21.png">

**Comment by hectoritr** [comment]
@asimjawad

**Comment by asimjawad** [comment]
That is from the plugin @hectoritr, I will make it such a way that when data is loading just show a progress indicator and then load the graph

**Comment by hectoritr** [comment]
We will re do this with the new UI
