### ISSUE TITLE
Navigation Drawer

### ISSUE THREAD

**Issue by hectoritr** [OTTAA-Project/ottaa_project_flutter#28]
**Screenshot of the feature to be developed.**
 
![Screenshot_1641927783](https://user-images.githubusercontent.com/12820318/149005663-70a9102e-9411-462f-9c42-687497cf15cb.png)

**Describe the solution you'd like**
A navigation drawer must appear from the left with the proposed design, in case the Swipe gesture cannot be achieved a small indicator must be present to click and open it. 
In the screenshot is the full-feature navigation drawer, to start we will have less options on it, when a new feature is developed we will add it to the navigation drawer.  

**Additional context**
Add any other context.

**Action Plan**
Add an Action Plan with Checkboxes on key things you have to achieve to complete this task.
- [x] Design Navigation Drawer
- [x] Add Setting screen
- [x] Add Tutorial (This has to link to the Screen that shows the option to learn about OTTAA during Tutorial)
- [x] Add Close App
- [x] Add Logout

**Comment by hectoritr** [comment]
@asimjawad Attaching the OTTAA logo in white. 

![isologotipo blanco](https://user-images.githubusercontent.com/12820318/150349197-12678e50-85d0-4614-8738-c0bbe7be05ef.png)

**Comment by hectoritr** [comment]
Re-opening this issue with small details from testing. 

- [ ] Remove Location Option
- [ ] Make Mute functionality work or remove. (Mute should mute the TTS)
- [ ] Remove Generate Report
