### ISSUE TITLE
JSON 💀 Database

### ISSUE THREAD

**Issue by hectoritr** [OTTAA-Project/ottaa_project_flutter#3]
**Is your feature request related to a problem? Please describe.**
- [x] YES
- [x] NO
If YES  please write a clear and concise description of what the problem is. 

**Describe the solution you'd like**
The app should load a JSON database, stored in firebase, with the user’s pictograms, the user’s groups, and created sentences.

**Action Plan**
Add an Action Plan with Checkboxes on key things you have to achieve to complete this task.
- [x] Load JSON from File
- [x] Create Picto object
- [x] Load JSON from Firebase
