### ISSUE TITLE
Firebase Crashlytics

### ISSUE THREAD

**Issue by hectoritr** [OTTAA-Project/ottaa_project_flutter#31]
**Describe the solution you'd like**
Implement Firebase crashlytics, to track all crash and ANR in all platform and log the source of the crash. 

**Action Plan**
Add an Action Plan with Checkboxes on key things you have to achieve to complete this task.
- [x] Implement Firebase Crashlytics for Android
- [ ] Implement Firebase Crashlytics for web
- [x] Implement Firebase Crashlytics for iOS
- [x] Track everything on Firebase Console

**Comment by asimjawad** [comment]
crahslytics are not supported for web

**Comment by hectoritr** [comment]
> @hectoritr crahslytics are not supported for web

Ok, no problem we put it in a Waiting list, but is done for Android and iOS?

**Comment by asimjawad** [comment]
yes it is
