### ISSUE TITLE
About OTTAA

### ISSUE THREAD

**Issue by hectoritr** [OTTAA-Project/ottaa_project_flutter#32]
**Screenshot of the feature to be developed.**
 
![Screenshot_1641927794](https://user-images.githubusercontent.com/12820318/149007076-8900173b-0a20-45ce-adbb-a1101d66b214.png)

**Describe the solution you'd like**
Implement a screen with information about OTTAA, the user, the account type, the current device and other information. Also, a button to Contact support should be present, when pressed this button must mail to support@ottaaproject.com with all the abovementioned information. 

This needs issue #28 to be finished first. 

**Action Plan**
Add an Action Plan with Checkboxes on key things you have to achieve to complete this task.
- [x] Design UI
- [x] Load Account & Account type
- [x] Load current version & Installed version
- [x] Get Device name
- [x] Contact Support button.

**Comment by hectoritr** [comment]
Please find attached the assests for about_ottaa screen

about_ottaa_xml.zip

**Comment by asimjawad** [comment]
where to find the information for about page e.g current version, installed version and account type

**Comment by asimjawad** [comment]
@hectoritr need the following resources:
The drawable.

**Comment by hectoritr** [comment]
Re-opening with minor details

- [ ] Not showing the user current account
- [ ] Not showing the device Name

**Comment by asimjawad** [comment]
@hectoritr can you give me the platforms name where it is not showing the name of device.

**Comment by hectoritr** [comment]
On Chrome with Mac
