### ISSUE TITLE
Share

### ISSUE THREAD

**Issue by hectoritr** [OTTAA-Project/ottaa_project_flutter#34]
**Is your feature request related to a problem? Please describe.**
- [ ] YES
- [ ] NO
If YES  please write a clear and concise description of what the problem is. 

**Describe the solution you'd like**

**Additional context**

**Action Plan**
Add an Action Plan with Checkboxes on key things you have to achieve to complete this task.
- [ ] Task A
- [ ] Task B

**Comment by asimjawad** [comment]
@hectoritr 

- [ ]  Share Audio over Web
- [ ] generate audio over mobile platforms
- [ ] generate string to share over mobile platforms
- [ ] generate string to share over web platforms
- [ ] generate picture over mobile platforms
- [ ] generate picture over web platforms

For now I have came to conclusion that we are not able to share audio over web platforms. 
I will also required some kind of explanation about what we want to achieve over web, for mobile it is clear to me and I am working on that.

**Comment by asimjawad** [comment]
the whatsapp one is not working...
I am only able to put text in a email for now and same can be done for picture which we are creating...
The audio is a no no for web.

**Comment by hectoritr** [comment]
@asimjawad Image sharing is not working in Mac or Lenovo, just hangs on the Circle Progress bar. 

Text works fine. 

Also, if audio is "no no" for web, shouldn't show the option as an active button. Remove, disable it, or add a Toast saying that is not working yet.
