### ISSUE TITLE
Mobile design.

### ISSUE THREAD

**Issue by hectoritr** [OTTAA-Project/ottaa_project_flutter#38]
**Describe the solution you'd like**
Here are described minor bugs & UI improvements for the mobile version of the OTTAA Project flutter version. 

Tested on emulator 
 - Nexus 10 API 27
 - Pixel 3a API 27

**Action Plan**

**Onboarding**
- [x] Top button is showing incorrect text, probably due to automated translation.
- [x] Top button does not match the orange on the other buttons.  

**Tutorial**
- [x] Not showing step3.long string. 

**Home**

<img width="151" alt="Screen Shot 2022-08-08 at 15 40 04" src="https://user-images.githubusercontent.com/12820318/183490136-1e9bc059-bbdd-4ed7-8636-c42f7f8b8933.png">

<img width="1008" alt="Screen Shot 2022-08-08 at 15 40 10" src="https://user-images.githubusercontent.com/12820318/183490209-3bfe8f52-7c3c-43aa-93a0-716a6ea2d804.png">

![Screenshot_1659984167](https://user-images.githubusercontent.com/12820318/183490718-c3faea28-2426-4328-bb39-3570aba5e955.png)

- [x] Not enough margin on the Games button.
- [x] Bottom buttons are not centered on the orange bar.
- [x] When choosing the first pictogram, something weird happens to the UI. When choosing a 2 picto it fixes itself.

**Games**
![Screenshot_1659984319](https://user-images.githubusercontent.com/12820318/183491175-bd74efca-aafe-4b0a-abff-5fb0d0529f12.png)

- [ ] Reduce cardview bottom margin (Similar to Grupos or Picto in single view)
- [ ] Reduce cardview top margin (make aspect ratio similar to the picto aspect ratio)
- [ ] Word level on cardview is not translated

Game Grupo chooser
![Screenshot_1659984050](https://user-images.githubusercontent.com/12820318/183491641-05492bd2-ff5e-4f84-899d-bc8689e226ee.png)

- [ ] Weird radius on the orange bar, make same as Grupo or Picto single view.

**Comment by hectoritr** [comment]
Action plan for Pixel 3a

**Splash screen**
- [ ] Not showing any splash screen, just a white screen. (Log throwing this "A splash screen was provided to Flutter, but this is deprecated. See flutter.dev/go/android-splash-migration for migration steps.")

**Login screen**
![Screenshot_1659984853](https://user-images.githubusercontent.com/12820318/183492968-7579fb6a-7725-4514-af69-47ac7d10f7ec.png)
- [ ] Give more height to Login buttons. 

**Onboarding**
![Screenshot_1659984853](https://user-images.githubusercontent.com/12820318/183493204-c6c133df-22a7-430e-a83a-9043c17cd700.png)

- [ ] Right overflow
- [ ] Not showing Birthday chooser

**Comment by asimjawad** [comment]
@hectoritr ok, working on it, will create a separate branch for it

**Comment by asimjawad** [comment]
@hectoritr check the mobile design branch,

**Comment by hectoritr** [comment]
> @hectoritr check the mobile design branch,

On it!

**Comment by hectoritr** [comment]
@asimjawad I've updated the issue with the latest from Mobile Branch
