### ISSUE TITLE
Paid User Version

### ISSUE THREAD

**Issue by hectoritr** [OTTAA-Project/ottaa_project_flutter#39]
**Screenshot of the feature to be developed.**
 
![Screenshot_1646336004](https://user-images.githubusercontent.com/12820318/156639466-f0c0a0d7-2f20-41e7-9804-3fa4c7fa86fe.png)

![Screenshot_1646336070](https://user-images.githubusercontent.com/12820318/156639472-afd905eb-9357-4842-ad87-46b1ab8aefe2.png)

![Screenshot_1646336077](https://user-images.githubusercontent.com/12820318/156639480-2588ba62-ecff-460e-a706-9531480fefc0.png)

**Describe the solution you'd like**
We need to block some feature to free user's, user with a premium account should be able to access this features. 

The block screen should be similar to the ones from the Screenshot, the green button and Login button can be improved. 
A pageview with automated transition 5 sec each view, should be implemented showcasing the different benefit of subscribing to the Premium version.  

Strings and Assets for the Pageview will be provided. 

Green button, should lead to our payment Gateway with the standard licence. Link will be provided

Login button, should be gray and do a full logout and go to login page to change user. 

**Action Plan**
Add an Action Plan with Checkboxes on key things you have to achieve to complete this task.
- [x] BlockScreen UI implemented
- [x] Create Purchase button
- [x] Create Login button
- [x] Create and populate Pageview

**Comment by asimjawad** [comment]
@hectoritr 
what do you mean by this sentence "A pageview with automated transition 5 sec each view, should be implemented showcasing the different benefit of subscribing to the Premium version."

**Comment by hectoritr** [comment]
> @hectoritr what do you mean by this sentence "A pageview with automated transition 5 sec each view, should be implemented showcasing the different benefit of subscribing to the Premium version."

As is in the Android version "A screen with a carrousel-like" feature that displays icons and text. Each icon should be 5-sec visible and then the next one should be displayed.

**Comment by hectoritr** [comment]
Features to be implemented: 
-Games
-Report
-Accesibility
-Picto & Group Edit
-GPS location

@gonojuarez will provide Strings and Assets for the screen.

**Comment by asimjawad** [comment]
@hectoritr 
correct me if I am wrong here. You want to change the icon and the text after every 5 seconds in the paid version screen?

**Comment by asimjawad** [comment]
@hectoritr 
where to take the user if he click on the purchase button.

**Comment by hectoritr** [comment]
> 

Yes, exactly like it does in the Android app now.
