### ISSUE TITLE
Firebase Hosting

### ISSUE THREAD

**Issue by hectoritr** [OTTAA-Project/ottaa_project_flutter#4]
**Is your feature request related to a problem? Please describe.**
- [x] YES
- [x] NO
If YES  please write a clear and concise description of what the problem is. 

**Describe the solution you'd like**
We need people to access OTTAA Project on a public URL, like app.ottaaproject.com
The app should be hosted on Firebase and linked to the right URL. 

**Action Plan**
Add an Action Plan with Checkboxes on key things you have to achieve to complete this task.
- [x] Host App on Firebase
- [x] Link URL
- [ ] Add Beta URL
- [ ] Add CI and create support for Automated Testing.

**Comment by mal2tin** [comment]
I need access to the CPANEL, or to carry out the process together with whoever has access.

**Comment by hectoritr** [comment]
Ready, we just need to create the beta channel
