### ISSUE TITLE
Different Json for different Language and type of user

### ISSUE THREAD

**Issue by hectoritr** [OTTAA-Project/ottaa_project_flutter#48]
**Describe the solution you'd like**
When a new user is logging in, we should provide a trained JSON model for their predictions based on their preferred gender and age.

We are covering several types of genders:

- Male
- Female
- Fluid
- Binary
- Other

And 3 age types:

- Adult
- Young
- Child

So, we would need to create 15 different models according to the possible combinations. 
@gonojuarez will fetch the last data from the database.

@lopezjuanma96 will train and provide the different models.
We can use Miguel's algorithm but also use the current metadata on the JSON file to improve the model, like the user's age and time of day of the sentence to TAG them.

@asimjawad will do the flutter implementation. 

Comment below when your work is done. 

**Additional context**
Add any other context.

**Action Plan**
Add an Action Plan with Checkboxes on key things you have to achieve to complete this task.

- [x] Download data from OTTAA's database.
- [x] Create models (15).
- [x] Review models by field experts. 
- [x] Download correct model on Login.

**Comment by lopezjuanma96** [comment]
- [ ] JSON with phrases, date and user
- [ ] search user database for gender and age of each user and assign to phrase to generate dataset
- [ ] aside from using dataset to train, search for more used pictograms for each category and assign the tag to that picto
- [ ]  search for more used pictograms for each time of day (of the for available tags) and assign the tag to that picto
- [ ] since some pictos already have tags, assign by the app or the users, we might generate two type of tags "calculated" and "assigned" and see if we can then compute something out of that comparison
- [ ]

**Comment by lopezjuanma96** [comment]
ISSUES REGARDING THE PHRASES JSON:

Look at this example of a phrase JSON:

{"frase":"Hola Buen día tengo castillo ","frecuencia":3,"complejidad":{"valor":0,"pictos componentes":[{"id":377,"esSugerencia":false},{"id":379,"horario":["MANANA"],"esSugerencia":false,"hora":["MANANA"]},{"id":49,"esSugerencia":false},{"id":945324633}]},"fecha":[1637327873525,1637327994767,1637329129227],"locale":"es","id":0}

some things we have to decide are:

- [ ] What do we do with an id like the last one? I believe that value is because it was a picto created or downloaded. Adding it to the database can be done but it will be complex since there's no simple relation between picto position and word position -in this case it's at the end of the phrase, but should it be in the middle, it's much harder and propense to error-.
- [ ] If we are going to use the tags set on the pictos aside from the ones "calculated" with the timestamps and user data, we have to solve why one picto has a key "horario" and the other has a key "hora".

**Comment by lopezjuanma96** [comment]
Span of keys and tags the app is using at the moment:

'key': {'TAGS'}

'hora': {'MANANA', 'MEDIODIA', 'TARDE', 'NOCHE'}
'edad': {'ADULTO', 'JOVEN', 'NINO'}
'sexo': {'FEMENINO', 'MASCULINO', 'BINARIO', 'FLUIDO', 'BINARIO'}
'ubicacion': {'ESTADIO', 'PARQUE',... //we are not using it for now

**Comment by lopezjuanma96** [comment]
Process for developing a new model specific to a certain group:

- [ ] Obtain phrases to train Miguel's Algorithm
- [ ] Train Miguel's Algorithm
- [ ] Generate phrases with Miguel's Algorithm and Tokenize them into the picto database
- [ ] Search for the images of new pictos from the tokenization

Process of updating tags from user's phrases:
- [ ] get phrases database with gender, age and timestamp data
- [ ] extract data from each phrase and add tag frequency to each picto in the picto database

**Comment by lopezjuanma96** [comment]
Possible Sources for Training Miguel's Algorithm:

- Medical:
- - https://www.kaggle.com/competitions/nbme-score-clinical-patient-notes/data?select=patient_notes.csv
- - https://www.kaggle.com/datasets/chaitanyakck/medical-text
- - https://mimic.mit.edu/docs/about/
- - https://github.com/curai/medical-question-pair-dataset

**Comment by lopezjuanma96** [comment]
Possible Sources for Training Miguel's Algorithm:

- Law/Court: we might find court records, specially transcripts to be useful
- - https://pacer.uscourts.gov/
- - https://www.in.gov/courts/public-records/
- - https://www.courts.ca.gov/42512.htm
- - https://www.fedcourt.gov.au/services/access-to-files-and-transcripts/transcript
- - https://www.rev.com/blog/how-to-get-court-transcripts

**Comment by lopezjuanma96** [comment]
Whis might be useful: https://convokit.cornell.edu/documentation/datasets.html

**Comment by lopezjuanma96** [comment]
Scientific Dataset: https://www.kaggle.com/datasets/Cornell-University/arxiv/code

The full dataset is REALLY large (1.1TB and growing), but we can download the metadata which have all titles, abstract, authors, categories, etc. With it we can select categories for each model and train with the abstracts or download some of the papers.

**Comment by hectoritr** [comment]
**Download correct model on Login.**
When the user starts the app and select the Gender and DoB. We should store those value to be use by the prediction algorithm. 

<img width="1440" alt="Screen Shot 2022-08-25 at 12 17 48" src="https://user-images.githubusercontent.com/12820318/186704713-4cd868ff-25af-4b37-86bb-81dbef2e3260.png">

The options currently are

Gender
- Male
- Female
- Other

Age (calculate the right TAG based on the DoB
- Child 0-15 yr
- Young 15-25 yr
- Adult <25

These values should be stored as profile info of the user and used in the prediction. 

Then based on the gender you have to download the right JSON dataset. 
- picto_es_male
- picto_es_fem
- picto_es_other

**Comment by hectoritr** [comment]
@asimjawad is this done? Download the right model accordint to the user?

**Comment by asimjawad** [comment]
@hectoritr we did not do this. add the required api here and I will be on it.

**Comment by asimjawad** [comment]
@lopezjuanma96 add them here.

**Comment by asimjawad** [comment]
reopening this issue, because work on some parts was not done.

**Comment by hectoritr** [comment]
@asimjawad here is what I found so far

This was on the default database
<img width="304" alt="Screen Shot 2022-10-05 at 10 40 32" src="https://user-images.githubusercontent.com/12820318/194075212-11143336-2d1c-4ad2-b3a8-20520e02bab5.png">

This was on the testing database
<img width="331" alt="Screen Shot 2022-10-05 at 10 41 29" src="https://user-images.githubusercontent.com/12820318/194075379-7376e2cc-16b0-486f-b4d1-35450149c90b.png">

**Comment by asimjawad** [comment]
@hectoritr can you explain this a further. I will see it in the morning.

**Comment by asimjawad** [comment]
@hectoritr we are using default one.

**Comment by asimjawad** [comment]
and as I told you that, the jsons are only loaded when a user will create a new account...
and they will be choosing their gender. At that time we will upload and save the Json according to their gender.
