### ISSUE TITLE
Add Group and Add Pictogram

### ISSUE THREAD

**Issue by hectoritr** [OTTAA-Project/ottaa_project_flutter#49]
**Screenshot of the feature to be developed.**
 

**Describe the solution you'd like**

**Additional context**
Add any other context.

**Action Plan**
Add an Action Plan with Checkboxes on key things you have to achieve to complete this task.
- [ ] Task A
- [ ] Task B

**Comment by hectoritr** [comment]
Things that are not working
- [ ] Add a new Picto to a new Group and to an old Group. 
- [ ] Popup menu to EDIT or DELETE a Group.
- [ ] When going back from creating a Picto or a Group is not showing the newly created picto.

**Comment by asimjawad** [comment]
@hectoritr  can you send me the screenshots of logs for the first issue and for 3rd one have you tried going to the bottom of the page?

**Comment by hectoritr** [comment]
Yes, I tried.

**Comment by hectoritr** [comment]
I've found this error during testing on Android when loading an image from Camera and from Gallery. 

![Screenshot_1651260604](https://user-images.githubusercontent.com/12820318/166060191-355802dd-c6df-40db-913b-d0c8b74bfd18.png)

Also is not loading properly the images on the Dialog

![Screenshot_1651260652](https://user-images.githubusercontent.com/12820318/166060262-bd28be7b-3e87-430b-bb12-7e1edc34ec70.png)
