### ISSUE TITLE
More Pictograms

### ISSUE THREAD

**Issue by hectoritr** [OTTAA-Project/ottaa_project_flutter#5]
**Is your feature request related to a problem? Please describe.**
- [x] YES
- [x] NO
If YES  please write a clear and concise description of what the problem is. 

**Describe the solution you'd like**
When the user press the “more pictograms” button, placed on the left side of the speak button. The app should load and display the next 4 pictograms. The app sorts the pictograms based on a recommendation algorithm that will be provided to the developers.

**Action Plan**
Add an Action Plan with Checkboxes on key things you have to achieve to complete this task.
- [x] Implement Scoring algorithm
- [x] Implement More Pictogram button
- [x] Load the related Pictograms

**Comment by hectoritr** [comment]
Scoring still need user data to be useful.
