### ISSUE TITLE
Favorites Sentences Screen

### ISSUE THREAD

**Issue by hectoritr** [OTTAA-Project/ottaa_project_flutter#51]
**Screenshot of the feature to be developed.**
 
![jjj](https://user-images.githubusercontent.com/12820318/155728252-41cd76f0-1f6e-41c7-864a-b223260e4429.png)

**Describe the solution you'd like**
Unify the UI of the app. Replace current UI of Favorites Sentences with the proposed Screenshot. Keep the transparent background of Favorites Sentences. 

**Action Plan**
Add an Action Plan with Checkboxes on key things you have to achieve to complete this task.
- [x] Replace current Bottom Bar of Favorites with the one from Groups
- [x] Make the app speak with the Circular Button
- [x] Go back when press close
- [x] Search the sentences with the Search button.

**Comment by hectoritr** [comment]
Done, this closes #51
