### ISSUE TITLE
Pre-release v1.0

### ISSUE THREAD

**Issue by hectoritr** [OTTAA-Project/ottaa_project_flutter#56]
**Describe the solution you'd like**
A set of small changes & bug's needed for the release. 

**Action Plan**
Add an Action Plan with Checkboxes on key things you have to achieve to complete this task.
- [x] Not adding relationships to the first abstract Picto on MainScreen, "Picto perro". 
- [x] Add Picto from Main Screen not working.
- [x] Make Picto show text in CAPSLOCK
- [x] Add "Toast" or SnackBar with text "We are working on this feature" for buttons without Implemented functionality (Games, Share, etc)
- [x] Add Toast or SnackBar with text "Choose a Picto to speak" when the user try to speak without choosing any pictogram.
- [x] Showing about_ottaa instead of proper text on NavigationBar
- [x] Change "Mudo" for Silenciar in Spanish on NavigationBar
- [x] Change size on Custom Subtitles not working
- [x] Caps Lock not working on Custom Subtitles. 
- [x] Add "Toast" or SnackBar with text "We are working on this feature" for Settings without Implemented functionality (Pictograms, Prediction, Accesibility)

**Comment by asimjawad** [comment]
@hectoritr will start working on them
