### ISSUE TITLE
v1.0 Feedback & Bugfix

### ISSUE THREAD

**Issue by hectoritr** [OTTAA-Project/ottaa_project_flutter#59]
**Screenshot of the feature to be developed.**
 

**Action Plan**

- [x] Change Toast for in progress Features for "Estamos trabajando en esta funcionalidad"
- [x] Change Title Sentences for "Most used Sentences"
- [x] Delete Picto not working
- [x] Add Grupo not working (might be solved with #49 )
- [x] When Editing a Picto, the image appears Gray until you go back.
- [x] Close button on Group gallery and Picto Gallery are misaligned
- [x] When searching if you press "Enter" the entire screen goes white. 
- [x] Search work for textual string and not the whole word (Example: if I search for "The Goat" the picto "Goat" does not appear on the search)
- [x] Change String TAGE for TAG
- [x] User account or email STILL NOT APPEARING on About OTTAA
- [x] On Tutorial a scrolling bar is appearing on some screens
- [x] on Tutorial Next button is not always aligned on the same place.

**Comment by asimjawad** [comment]
@hectoritr next button is always in the same place here..
![Screenshot_1650531095](https://user-images.githubusercontent.com/25550909/164418015-7c73389f-eb69-4489-ba94-4587099c5509.png)
![Screenshot_1650531101](https://user-images.githubusercontent.com/25550909/164418025-a99f8c11-17b5-4fef-8d25-cbe784402f13.png)
.

**Comment by asimjawad** [comment]
@hectoritr  where is this one  "**Change Title Sentences for "Most used Sentences"**"

**Comment by hectoritr** [comment]
> @hectoritr where is this one "**Change Title Sentences for "Most used Sentences"**"

On the Screen Most Used Sentences, you can find it by pressing the heart on Main Screen.

**Comment by asimjawad** [comment]
@hectoritr  you mean the favourite one

**Comment by hectoritr** [comment]
Minor bug @asimjawad "When clicking on Share" it's taking you to the tutorial. 
Also, still, the account is not appearing on "About OTTAA" that's really important to get good customer support. 

Let finish this issue as soon as possible so we can announce the release.

**Comment by asimjawad** [comment]
@hectoritr can you give me some google accounts to test it. on my account the email is coming null from firebase
