### ISSUE TITLE
Favorites ❤️

### ISSUE THREAD

**Issue by hectoritr** [OTTAA-Project/ottaa_project_flutter#6]
**Is your feature request related to a problem? Please describe.**
- [x] YES
- [x] NO
If YES  please write a clear and concise description of what the problem is. 

**Describe the solution you'd like**
When the user press the “favorites”, the heart-shaped button, a dialog should be prompted with the most used sentences from the users, these sentences are stored in a JSON database.

**Action Plan**
Add an Action Plan with Checkboxes on key things you have to achieve to complete this task.
- [x] Create Favorite layout
- [x] Load Sentences from JSON
- [x] Make the app speak the sentence when touched.
