### ISSUE TITLE
Firebase interface & dependency injection for DPG certification

### ISSUE THREAD

**Issue by hectoritr** [OTTAA-Project/ottaa_project_flutter#61]
**Screenshot of the feature to be developed.**
 

**Describe the solution you'd like**
We need to certify OTTAA as DPG (Digital Public Good) for that the only thing needed is to achieve platform independence from Firebase, for that what the DPG team suggest is to create dependency injection for all firebase interactions. 

Some tips and guidelines found.
 - https://medium.com/flutter-community/flutter-fast-dependency-injection-5748d956bb5c
 - https://blog.logrocket.com/dependency-injection-flutter-using-getit-injectable/

Ideally with very little work another provided can be implemented in the code and should work. 

**Action Plan**
Add an Action Plan with Checkboxes on key things you have to achieve to complete this task.
- [x] Create Action Plan

**Comment by asimjawad** [comment]
Created a DataController class which is responsible for providing the data to the controllers in the app and also take data from them to upload onto the firebase. The concept is that the firebase can be replaced by the other developers from the DataController class and they can use another backend services if they want to. Th DataController is connected to the FriebaseDataBaseRepository which is just a place holder class for the functions from the FirebaseDatabaseServices and this class includes the all implementation for the firebase database services. Below are some of the screenshots: 
![Screenshot 2022-05-24 at 11 40 17 AM](https://user-images.githubusercontent.com/25550909/169965362-3d264d52-f2c1-4a62-a5ca-bf1c64e0fe2c.png)
![Screenshot 2022-05-24 at 11 39 58 AM](https://user-images.githubusercontent.com/25550909/169965391-8ede47f0-2f96-4de8-9e1b-7ab71db7dbf5.png)
![Screenshot 2022-05-24 at 11 39 42 AM](https://user-images.githubusercontent.com/25550909/169965399-b504cabd-e130-4c86-88aa-d983ebf35364.png)

**Comment by hectoritr** [comment]
For Auth we can check out https://openid.net/connect/

**Comment by hectoritr** [comment]
After talking with a mentor. He said that if we can share an example of an implementation for each Controller we should be good to go. 

Example for fetch data, fetch auth and log Analytics event. 

- [ ] Firebase Database service. (Supabase Database service example)
- [ ] Auth service. (OpenID connect example)
- [ ] Remove/Refactor FirebaseAnalytics as the previous ones. 


PS: What is Firebase_Database_repository for?

**Comment by asimjawad** [comment]
Firebase_database_repository is just a file to follow the pattern we are having in the app, a repository can access multiple services for the same thing, e.g, if we shift from freebase to Supabase we just need to add the services for it and link it to the repository and no need to change the other things in the app, Kind of like the MVVM @hectoritr

**Comment by hectoritr** [comment]
https://digitalpublicgoods.net/standard/

PR to OTTAA's DPG
https://github.com/DPGAlliance/publicgoods-candidates/pull/928

**Comment by hectoritr** [comment]
DPG team approved the platform independence! Kudos @emirchus @asimjawad
