### ISSUE TITLE
v1.1 Bugfix & UI details

### ISSUE THREAD

**Issue by hectoritr** [OTTAA-Project/ottaa_project_flutter#63]
**Screenshot of the feature to be developed.**
 

**Describe the solution you'd like**
Collection of minor bug fixes and UI details to fix for version v1.1.

**Action Plan**
Add an Action Plan with Checkboxes on key things you have to achieve to complete this task.

Login Screen
- [ ] Change the text "Hello Please register to continue" to "Hello, welcome to OTTAA Project, the first predictive communication platform for people with speech impairments, please login with your account and fill in some data to benefit from our prediction." 

Onboarding
- [ ] Radius is missing on the white card view.
- [ ] Textview widgets are too separated, establish a margin, and put them all together from top to bottom.
- [ ] Fetch Name, Gender and Date or birth from Google of Facebook account and fill the data.
- [ ] Make the OTTAA Logo same size as the next screen.

Main Screen
- [ ] Make the Orange bottom control bar, the same size as the Group control bar.
- [ ] Make radius on vertical orange bar same as Groupo left and right arrow buttons.
- [ ] Add a radius to the corner that joins the bottom bar with vertical orange bars.
- [ ] Change "Game" icon button to a Joystick icon, as in OTTAA to have consistency with OTTAA users.

**Comment by asimjawad** [comment]
@hectoritr lets do these changes in the next iteration...

**Comment by asimjawad** [comment]
send me the resolution (dimensions of the screen) for the 14 inches

**Comment by asimjawad** [comment]
also send me the size of the (Lenore) @hectoritr

**Comment by hectoritr** [comment]
> * Lenovo Ideapad Flex 14" Resolution 1920 x 1080

It's on the description - Lenovo Ideapad Flex 14" Resolution 1920 x 1080

**Comment by asimjawad** [comment]
I tried fetching the sensitive information like gender and DOB, but google is not allowing that and Facebook might allow us to do that..
I am going through their documentation and It can take a while to read It all...
@hectoritr

**Comment by hectoritr** [comment]
Final improvements for v1.1

Login Screen

- [ ] Facebook button is still not aligned, does not adjust to different screen sizes, and now is plain and it has no interactions, shadows, etc. Better to go back to the previous button and align it better. 

<img width="323" alt="Screen Shot 2022-07-27 at 13 15 52" src="https://user-images.githubusercontent.com/12820318/181297755-d6afa99c-d6f0-4a0e-b065-3cf8217fc654.png">


Main Screen

- [ ] Circle Progress Bar showing all the time
- [ ] The radius implemented is too small
- [ ] Pictograms are trimmed on the bottom by a margin (On Mac)
- [ ] Orange bar, still not the same as Grupos. 

<img width="432" alt="Screen Shot 2022-07-27 at 13 14 35" src="https://user-images.githubusercontent.com/12820318/181297792-08fb1bc8-408b-4e27-a547-964ad86c031c.png">

Grupos screen

- [ ] Pictogram still stretched on single view mode, should have same proportions as the Picto on Main Screen.

EditPicto Screen

- [ ] Cardview still have different sizes, are not aligned
- [ ] "Add Group" string might not be translated, there is some Texts in English and some in Spanish


<img width="908" alt="Screen Shot 2022-07-27 at 13 19 25" src="https://user-images.githubusercontent.com/12820318/181298541-93eab392-d993-491e-9108-bcd1a231bda4.png">

<img width="1031" alt="Screen Shot 2022-07-27 at 13 21 34" src="https://user-images.githubusercontent.com/12820318/181298770-bc6f630d-3778-42b4-816c-88e2a0219af2.png">

**Comment by asimjawad** [comment]
did you tested these features on the web or the mobile?
@hectoritr

**Comment by hectoritr** [comment]
> did you tested these features on the web or the mobile? @hectoritr

As we said, we are focusing on web for this release, so it's tested on web.

**Comment by asimjawad** [comment]
<img width="1680" alt="Screenshot 2022-07-28 at 8 05 48 PM" src="https://user-images.githubusercontent.com/25550909/181572297-9c4f13a5-4645-4a4e-aee8-9c41b8e56a7a.png">
The language is already there...

I will look into the other ones...

**Comment by asimjawad** [comment]
https://user-images.githubusercontent.com/25550909/181573014-5bcd3eb2-b390-4ece-a0ec-b481ae98b2e1.mov

The circularProgessIndicator is hiding itself

**Comment by hectoritr** [comment]
@asimjawad try using this plugin https://pub.dev/packages/flutter_signin_button for Login

**Comment by hectoritr** [comment]
@asimjawad please review unfinished Checkboxes on this issue, also a lot of them were ticked but not implemented, at least for Web, our focus and priority. 

Also, 
- [ ] In Most used sentences, the circularProgessIndicator does not disappear. 
- [ ] Add the same radius on the bottom orange bar, same as Main Screen and Grupos
