### ISSUE TITLE
Login Process

### ISSUE THREAD

**Issue by hectoritr** [OTTAA-Project/ottaa_project_flutter#7]
**Is your feature request related to a problem? Please describe.**

-NO
If YES  please write a clear and concise description of what the problem is. 

**Describe the solution you'd like**
We need a Login Process exactly like the one in the OTTAA Android App (see attached), all the assets are available in the provided folder. 
The user data stored from the user should be saved on the appropriate entry on the Database.

**Action Plan**
Add an Action Plan with Checkboxes on key things you have to achieve to complete this task.

- [x] Login Screen IA.  Use Firebase to do the user authentication with Google
- [x] Login Screen IB.  Use Firebase to do the user authentication with Facebook
![Login Screen I](https://user-images.githubusercontent.com/12820318/124981737-4bbf7500-e00c-11eb-800a-81706c8d7548.png)

- [x] Login Screen II. 
![Login Screen II](https://user-images.githubusercontent.com/12820318/124981739-4c580b80-e00c-11eb-8cb5-caf06334cc99.png)

- [x] Login Screen III. Is different from the designed, should use the same background but add 3 button that links to different ways of learning about OTTAA
![Screenshot_1625774039](https://user-images.githubusercontent.com/12820318/124982529-2ed77180-e00d-11eb-9bb0-a217e338cda1.png)

- [x] Login Screen IV. Here the user chooses an avatar or can choose a picture from their computer as well to use as Avatar, the image should be saved on the database as well. 
![Login Screen 4](https://user-images.githubusercontent.com/12820318/124981733-4a8e4800-e00c-11eb-93b8-a6ea902841f0.png)

**Comment by hectoritr** [comment]
Here is the file to the detailed Realtime Database structure https://docs.google.com/document/d/14QBt6fA8oY0SNjGr9Ht90YuewY5EhzHHdq1Wud4guRY/edit
 
Please add comments as needed
