### ISSUE TITLE
iOS app package & publish

### ISSUE THREAD

**Issue by hectoritr** [OTTAA-Project/ottaa_project_flutter#81]
**Screenshot of the feature to be developed.**
 

**Describe the solution you'd like**
Compile and test an iOS package, also finish the App Store registry and publish it. 

**Action Plan**
Add an Action Plan with Checkboxes on key things you have to achieve to complete this task.
- [x] Compile for iOS
- [ ] Test on iPad
- [x] Enroll in Apple Developers
- [x] Publish App

**Comment by hectoritr** [comment]
https://codewithchris.com/submit-your-app-to-the-app-store/

https://developer.apple.com/programs/enroll/
