### ISSUE TITLE
Subtitles

### ISSUE THREAD

**Issue by hectoritr** [OTTAA-Project/ottaa_project_flutter#9]
**Is your feature request related to a problem? Please describe.**
-  NO
If YES  please write a clear and concise description of what the problem is. 

**Describe the solution you'd like**
When the user makes the app speak, it should prompt a Subtitle with the sentence in Capital Letter, and the Avatar image. 

**Additional context**

**Action Plan**
Add an Action Plan with Checkboxes on key things you have to achieve to complete this task.
- [x] Make the subtitle
- [x] Put the avatar in the subtitle
- [ ] Make the Font size customizable

![Screenshot_1625774602](https://user-images.githubusercontent.com/12820318/124983572-80ccc700-e00e-11eb-9bc3-0bcb48942612.png)

**Comment by hectoritr** [comment]
Add same margin for left - top - bottom. 

<img width="728" alt="Captura de Pantalla 2021-12-10 a la(s) 09 46 27" src="https://user-images.githubusercontent.com/12820318/145576373-97ed5923-976e-4389-8fb7-2a055a0a3a78.png">

**Comment by hectoritr** [comment]
We still need to do the font size customizable, it does not change the size, and does not change from ALL CAPS LOCK to Caps on the first letter. @asimjawad

**Comment by asimjawad** [comment]
Ok, I will add the text changing and add also the CAPS LOCK one too. @hectoritr
